### ISSUE TITLE
Feat(sitemap)

### ISSUE THREAD

**Issue by AugustinMauroy** [belgiumJS/belgiumjs.github.io#36]
We should use [next-sitemap](https://www.npmjs.com/package/next-sitemap?activeTab=readme). Have siteMap is just to improve SEO

**Comment by Michael-Liendo** [comment]
Hi Augustin! You can explain more for the issue? I can help you.
It would be just using next-sitemap to generate a sitemap automatically for each build?

**Comment by AugustinMauroy** [comment]
> It would be just using next-sitemap to generate a sitemap automatically for each build?

Exactly! And to give the sitemap in the robot.txt

**Comment by Michael-Liendo** [comment]
Vale! Yo creo que lo puedo hacer. Me lo puedes asignar?

**Comment by Michael-Liendo** [comment]
Okay, I think I can do it. Can you assign it to me?

**Comment by AugustinMauroy** [comment]
You can do it. I don't really assign an people.

**Comment by Michael-Liendo** [comment]
Perfect! I make the fork and send a pr with the changes. 😄
